ARG NODE_IMAGE=oven/bun:latest
FROM $NODE_IMAGE AS base
WORKDIR /app

FROM base AS setup
COPY package.json ./
RUN bun install
RUN bun run build

FROM base AS production
COPY --from=setup /app/.output ./.output
COPY . .

EXPOSE 3000
ENTRYPOINT [ "bun", ".output/server/index.mjs" ]
