ARG DOTNET_IMAGE=mcr.microsoft.com/dotnet/sdk:8.0
ARG DOTNET_RUNTIME_IMAGE=mcr.microsoft.com/dotnet/aspnet:8.0-jammy-chiseled

FROM $DOTNET_IMAGE AS base
WORKDIR /app

FROM base AS setup
COPY *.csproj ./
RUN dotnet nuget locals all --clear
RUN dotnet restore

FROM base AS prerelease
COPY --from=setup /app/ ./
COPY . ./
RUN dotnet publish -c Release -o out

FROM $DOTNET_RUNTIME_IMAGE AS runtime
COPY --from=prerelease /app/out .
EXPOSE 8080

ENTRYPOINT ["dotnet", "server.dll"]